### ISSUE TITLE
Match rule doesn't work in Greasemonkey

### ISSUE THREAD

**Issue by Ede123** [jamesgarfield/GitHubSourceTree#1]
In case you're not watching discussions on Greasy Fork:

> Hi,
> 
> this is a very good idea!
> 
> However in Greasmonkey this script cannot be installed because the `@match https://*github.com/*` is ignored because of an invalid host error.
> 
> Could you please fix it (probably it just needs an additional dot, e.g. `https://*.github.com/*`)
> 
> Regards,
> Eduard

_(copied from https://greasyfork.org/en/forum/discussion/3726/match-rule-doesn-t-work-in-greasemonkey)_

**Comment by jamesgarfield** [comment]
Thank you for this! I surf the script distribution sites sometimes to check in, but you're correct in thinking not very often ;-)

Should have a patch for you soon...
